# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://russmorley.net
title: Russell Morley
email: 
author: Russell Morley
description: > # "Write an awesome description for your new site here. 
  All things software testing!

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/rusty_rebel_
  - title: github
    url: https://github.com/Rusty84
  - title: linkedin
    url: https://linkedin.com/in/russell-morley-4087b6136

